# Generated by Django 3.2.7 on 2021-12-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default=None)),
                ('available', models.BooleanField(default=True)),
                ('last_rental_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_return_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
