# Generated by Django 3.2.11 on 2022-01-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_alter_rental_rental_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'Species'},
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
