# Generated by Django 3.2.11 on 2022-03-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_auto_20220130_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='user',
        ),
    ]
