# Generated by Django 3.2.11 on 2022-03-09 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0006_remove_cat_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='available',
        ),
    ]
