# Generated by Django 3.2.11 on 2022-03-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0007_remove_cat_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
