# Generated by Django 3.2.11 on 2022-03-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0009_auto_20220324_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('0', 'No status'), ('1', 'Pending'), ('2', 'Actual'), ('3', 'Finished'), ('4', 'Cancelled')], default='0', max_length=20),
        ),
    ]
